### ISSUE TITLE
"Class extends value undefined is not a constructor or null" Error

### ISSUE THREAD

**Issue by emirhanengn** [webdevian/adonis-pug#10]
Hello!

I installed this package and added provider to start/app.js. But he gave me an error. I added the fault as a picture. Where is the problem?

![7](https://user-images.githubusercontent.com/21215832/38167280-8de8be06-34e7-11e8-92c7-a7555e9a05c3.png)

**Comment by webdevian** [comment]
@emirhanengn Can you show me what's in your `start/app.js` and your `package.json`

**Comment by webdevian** [comment]
Closing since no response. I think the problem is you have the default viewProvider listed in app.js too.
