### ISSUE TITLE
`make:pug` is not a registered command

### ISSUE THREAD

**Issue by LucaGabi** [webdevian/adonis-pug#13]
Hi,

  I get this: `make:pug` is not a registered command when using the command in the docs to generate a view.

Thanks.

**Comment by webdevian** [comment]
Which version are you using? Did you register the provider in `start/app.js`? What does your console output when you use the `adonis` command on its own?

**Comment by LucaGabi** [comment]
It worked, I was doing something wrong..

Thanks.
