### ISSUE TITLE
Setup for for Adonis 4.0

### ISSUE THREAD

**Issue by deafwood** [webdevian/adonis-pug#3]
Can you provide setup instructions for the new Adonis 4.0 release?  Thanks!

**Comment by webdevian** [comment]
There is an adonis v4 branch that has not been published to npm yet (awaiting guidance on namespace - https://github.com/adonisjs/discussion/issues/56)

In the meantime you can add this line to your package.json dependencies to use it - 
`"adonis-pug": "git://github.com/webdevian/adonis-pug#adonis4"`

Add `'adonis-pug/providers/PugProvider'` to your providers in start/app.js

This is not fully tested, let me know how you get on

**Comment by webdevian** [comment]
@deafwood I am going to create a new version for Adonis4 today, based on the built in edge view provider so that it behaves in the same way

**Comment by webdevian** [comment]
@deafwood WIP here, it pretty much works but I need to write tests and documentation - https://github.com/webdevian/adonis-pug/tree/adonis-4-compatability

**Comment by webdevian** [comment]
@deafwood Version 4.0.0 released on NPM with new documentation
