### ISSUE TITLE
How to use flashMessage()

### ISSUE THREAD

**Issue by cbeulke** [webdevian/adonis-pug#5]
Hi, thanks  you for this great piece of work. I've been waiting for an Adonis4 compatible version for about 4 month and now it is here. Great! The only thing i struggle with is integrating the flashMessage() function in my templates. Is there an easy way to use this?

My related code looks like this:
```pug
if(flashMessage('error'))
    .alert.alert-danger(role='alert')= flashMessage('error')
  if(flashMessage('success'))
    .alert.alert-success(role='alert')= flashMessage('success')
```

The error i receive: `this.resolve is not a function` in `node_modules\@adonisjs\session\src\Session\FlashGlobals.js` line 20.

**Comment by ameneres** [comment]
@cbeulke struggling with the same. Have you been able to get it working?

**Comment by cbeulke** [comment]
@ameneres i did not try it again, but i implemented another template function via the hooks.js file. might work the same way.

here ist the function i wrote:

```
const { hooks } = require('@adonisjs/ignitor')

const dateformat = require('dateformat')

hooks.after.providersBooted(() => {
  const View = use('View')

  View.global('formatDate', function (date) {
    return dateformat(date, 'dd.mm.yyyy, HH:MM')
  })
})
```
as you see it is pretty easy so it might also work with some self-written ```flashMessage()``` function.

**Comment by ameneres** [comment]
thanks @cbeulke. I'll do that for now. Thought that was an "official" way of dealing with it.

**Comment by webdevian** [comment]
Could you try again?

I have the following code working ok - 

```jade
if flashMessage('message')
  .error
    p Error: #{flashMessage('message')}
```

If you're still getting problems can you show me your providers in app.js and dependencies from package.json
